name: Build and deploy Gatsby site

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/discord-message
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          success_message: ":hourglass_flowing_sand: Build started..."

      - uses: actions/setup-node@v4
        with:
          node-version-file: web/.nvmrc
          cache: npm
          cache-dependency-path: web/package-lock.json

      - uses: actions/configure-pages@v3
        with:
          static_site_generator: gatsby

      - run: npm install && npm run build
        working-directory: web

      - uses: actions/upload-pages-artifact@v2
        with:
          path: web/public

      - uses: ./.github/actions/discord-message
        if: always()
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          status: ${{ job.status }}
          success_message: ":white_check_mark: Build finished OK"
          error_message: ":red_square: Build failed"


  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/deploy-pages@v2
        id: deployment

      - uses: ./.github/actions/discord-message
        if: always()
        with:
          webhook_id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          status: ${{ job.status }}
          success_message: ":white_check_mark: Deploy completed. See the page at ${{ steps.deployment.outputs.page_url }}"
          error_message: ":red_square: Deploy failed"
